import { DossierComplet } from './types';

export const INITIAL_DOSSIERS: DossierComplet[] = [
  {
    id: 1,
    identifiantUnique: 'CIV-COMM-2025-00001',
    numeroRegistre: 'REG-2025-0001',
    anneeRegistre: 2025,
    folio: 'F-01',
    tome: 'T-01',
    dateDeclaration: '2025-01-15',
    heureDeclaration: '09:30',
    nomEnfant: 'TRAORÉ',
    prenomsEnfant: 'Amina Fatou',
    sexe: 'F',
    statutEnfant: 'Enfant',
    dateNaissance: '2025-01-14',
    heureNaissance: '08:30',
    lieuNaissance: 'Maternité Centrale',
    nomPere: 'TRAORÉ',
    prenomPere: 'Moussa',
    dateNaissancePere: '1990-05-12',
    agePere: 34,
    professionPere: 'Professeur certifié',
    domicilePere: 'Quartier Résidentiel, Lot 14',
    nomMere: 'KOUASSI',
    prenomMere: 'Aya Marie',
    dateNaissanceMere: '1994-08-20',
    ageMere: 30,
    professionMere: 'Commerçante',
    domicileMere: 'Quartier Résidentiel, Lot 14',
    nomDeclarant: 'TRAORÉ Moussa',
    qualiteDeclarant: 'Père',
    temoin: 'Dr. KOUAME Paul, Médecin accoucheur',
    observations: 'Déclaration effectuée dans le délai légal des 30 jours.',
    nomOfficier: 'M. KABLAN Jean',
    fonctionOfficier: 'Officier de l’État Civil Délégué',
    statutValidation: 'VALIDE',
    typeDocument: "Extrait d'acte de naissance",
    numeroDocument: 'DOC-2025-0001',
    dateDelivrance: '2025-01-15',
    heureDelivrance: '10:00',
    personneReception: 'TRAORÉ Moussa',
    confirmationLivraison: true
  },
  {
    id: 2,
    identifiantUnique: 'CIV-COMM-2025-00002',
    numeroRegistre: 'REG-2025-0002',
    anneeRegistre: 2025,
    folio: 'F-01',
    tome: 'T-01',
    dateDeclaration: '2025-02-02',
    heureDeclaration: '11:15',
    nomEnfant: 'DIOP',
    prenomsEnfant: 'Ibrahima Cheikh',
    sexe: 'M',
    statutEnfant: 'Légitime',
    dateNaissance: '2025-02-01',
    heureNaissance: '14:15',
    lieuNaissance: 'Clinique de la Paix',
    nomPere: 'DIOP',
    prenomPere: 'Amadou',
    dateNaissancePere: '1987-11-04',
    agePere: 37,
    professionPere: 'Ingénieur en Génie Civil',
    domicilePere: 'Avenue de la République',
    nomMere: 'SOW',
    prenomMere: 'Mariam',
    dateNaissanceMere: '1992-03-15',
    ageMere: 32,
    professionMere: 'Médecin pédiatre',
    domicileMere: 'Avenue de la République',
    nomDeclarant: 'DIOP Amadou',
    qualiteDeclarant: 'Père',
    temoin: 'Mme BARRY Aïcha, Sage-femme diplômée',
    observations: 'Certificat d’accouchement N° 452/MS annexé au registre.',
    nomOfficier: 'Mme DIALLO Fatoumata',
    fonctionOfficier: 'Adjointe au Maire en charge de l’État Civil',
    statutValidation: 'VALIDE',
    typeDocument: "Copie intégrale d'acte de naissance",
    numeroDocument: 'DOC-2025-0002',
    dateDelivrance: '2025-02-02',
    heureDelivrance: '11:45',
    personneReception: 'DIOP Amadou',
    confirmationLivraison: true
  },
  {
    id: 3,
    identifiantUnique: 'CIV-COMM-2025-00003',
    numeroRegistre: 'REG-2025-0003',
    anneeRegistre: 2025,
    folio: 'F-02',
    tome: 'T-01',
    dateDeclaration: '2025-02-18',
    heureDeclaration: '14:00',
    nomEnfant: 'BAMBA',
    prenomsEnfant: 'Yasmine Noura',
    sexe: 'F',
    statutEnfant: 'Enfant',
    dateNaissance: '2025-02-17',
    heureNaissance: '22:45',
    lieuNaissance: 'Centre Hospitalier Régional',
    nomPere: 'BAMBA',
    prenomPere: 'Seydou',
    dateNaissancePere: '1985-06-18',
    agePere: 39,
    professionPere: 'Comptable agréé',
    domicilePere: 'Boulevard Circulaire Sud',
    nomMere: 'KONE',
    prenomMere: 'Fatoumata',
    dateNaissanceMere: '1989-12-05',
    ageMere: 35,
    professionMere: 'Directrice d’école',
    domicileMere: 'Boulevard Circulaire Sud',
    nomDeclarant: 'BAMBA Seydou',
    qualiteDeclarant: 'Père',
    temoin: 'M. KONE Ousmane, Oncle paternel',
    observations: 'Mention de reconnaissance inscrite.',
    nomOfficier: 'M. KABLAN Jean',
    fonctionOfficier: 'Officier de l’État Civil Délégué',
    statutValidation: 'VALIDE',
    typeDocument: "Extrait d'acte de naissance",
    numeroDocument: 'DOC-2025-0003',
    dateDelivrance: '2025-02-18',
    heureDelivrance: '14:30',
    personneReception: 'BAMBA Seydou',
    confirmationLivraison: true
  }
];

export const INITIAL_NAISSANCES = INITIAL_DOSSIERS;
